server:
  port:
    8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true